server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: doc-service
  data:
    elasticsearch:
      cluster-nodes: ${ES_CLUSTER_NODE}
    minio:
      node: ${MINIO_NODE}
      user: ${MINIO_USER}
      password: ${MINIO_PASSWORD}
      bucket: ${MINIO_BUCKET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Devtools properties
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# management config
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1

# Other Service endpoints
endpoints:
  user-service: ${USER_SERVICE_ENDPOINT}

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# OpenAPI Config
openapi:
  service:
    title: Doc Service
    version: v${VERSION}

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
  com:
    mohit: INFO