server:
  port: ${SERVER_PORT}

spring:
  application:
    name: doc-service
  data:
    elasticsearch:
      cluster-nodes: ${ES_CLUSTER_NODE}
    minio:
      node: ${MINIO_NODE}
      user: ${MINIO_USER}
      password: ${MINIO_PASSWORD}
      bucket: ${MINIO_BUCKET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Other Service endpoints
endpoints:
  user-service: ${USER_SERVICE_ENDPOINT}

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
  com:
    mohit: TRACE