spring:
  application:
    name: mylink
  datasource:
    url: jdbc:mariadb://mysql.mohit:3306/mylink
    username: service_admin
    password: service@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
  com:
    mohit: TRACE