server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api_gateway

openapi:
  service:
    title: API Gateway
    version: 1.0.0
    url: http://localhost:8083

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /user-service/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: /doc-service/v3/api-docs
        name: Doc Service
        primaryName: Doc Service

# Logging properties
logging:
  level:
    root: INFO
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
  com:
    mohit: TRACE
