# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger.html

# Other Service endpoints
endpoints:
  user-service: ${USER_SERVICE_ENDPOINT}
  doc-service: ${DOC_SERVICE_ENDPOINT}

# Logging properties
logging:
  level:
    root: INFO
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
  com:
    mohit: TRACE
