server:
  port: 8081

spring:
  application:
    name: authnz-service

  # Devtools properties
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
    com:
      mohit: INFO