server:
  port: 8081

spring:
  application:
    name: authnz-service-dev

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      mohit: INFO