server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME}
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Jwt properties
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 21600000

# OpenAPI Config
openapi:
  service:
    title: User Service
    version: v${VERSION}
    url: user-service