server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework

spring:
  application:
    name: user-service-dev
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Management properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1

# Jwt properties
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 21600000

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

# OpenAPI Config
openapi:
  service:
    title: User Service
    version: v${VERSION}

# Security config
security-config:
  allowed-paths: >
    /api/auth/**,
    /swagger-ui/**,
    /v3/api-docs/**,
    /actuator/**,
    /h2-console/**
  cors-config:
    allowed-origins: >
      http://localhost:8081,
      http://api.mohit
    allowed-methods: >
      GET,
      POST
    allowed-headers: >
      Authorization,
      Content-Type
    registered-paths: >
      /**

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    com:
      mohit: INFO