server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Jwt properties
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 21600000

# Swagger properties
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# OpenAPI Config
openapi:
  service:
    title: User Service
    version: v${VERSION}

# Logging properties
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: INFO
  com:
    mohit: TRACE